# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: urlshortner
    ports:
      - 3306:3306
    networks:
      - urlshortner-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - urlshortner-network

networks: 
  urlshortner-network:
    driver: bridge